name: Ouputs between jobs
on:
  push:
    branches:
      - main
jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      item: ${{ steps.generate-version.outputs.version-number }}
    steps:
      - name: Generate version number
        id: generate-version
        run: echo "version-number=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Use the output
        run: echo "The version is ${{ needs.job-1.outputs.item }}"
        